
import { Montaga } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "@/context/authUserContext";

const inter = Montaga({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Project1 AuthApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}</body>
      </html >
    </AuthContextProvider>
  );
}

